/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/sms-gw/v1/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProviders"];
        put?: never;
        post: operations["createProvider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sms-gw/v1/providers/{provider_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: components["parameters"]["providerId"];
            };
            cookie?: never;
        };
        get: operations["getProvider"];
        put?: never;
        post?: never;
        delete: operations["deleteProvider"];
        options?: never;
        head?: never;
        patch: operations["updateProvider"];
        trace?: never;
    };
    "/api/sms-gw/v1/provider-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProviderTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sms-gw/v1/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTemplates"];
        put?: never;
        post: operations["createTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sms-gw/v1/templates/{template_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: components["parameters"]["templateId"];
            };
            cookie?: never;
        };
        get: operations["getTemplate"];
        put?: never;
        post?: never;
        delete: operations["deleteTemplate"];
        options?: never;
        head?: never;
        patch: operations["updateTemplate"];
        trace?: never;
    };
    "/api/sms-gw/v1/templates/{template_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: components["parameters"]["templateId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["previewTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sms-gw/v1/api-clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAPIClients"];
        put?: never;
        post: operations["createAPIClient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sms-gw/v1/api-clients/{client_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: components["parameters"]["clientId"];
            };
            cookie?: never;
        };
        get: operations["getAPIClient"];
        put?: never;
        post?: never;
        delete: operations["deleteAPIClient"];
        options?: never;
        head?: never;
        patch: operations["updateAPIClient"];
        trace?: never;
    };
    "/api/sms-gw/v1/api-clients/{client_id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: components["parameters"]["clientId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resetAPIClientPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sms-gw/v1/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listBlocks"];
        put?: never;
        post: operations["createBlock"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sms-gw/v1/blocks/{block_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                block_id: components["parameters"]["blockId"];
            };
            cookie?: never;
        };
        get: operations["getBlock"];
        put?: never;
        post?: never;
        delete: operations["deleteBlock"];
        options?: never;
        head?: never;
        patch: operations["updateBlock"];
        trace?: never;
    };
    "/api/sms-gw/v1/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMessages"];
        put?: never;
        post: operations["sendMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sms-gw/v1/messages/{message_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                message_id: components["parameters"]["messageId"];
            };
            cookie?: never;
        };
        get: operations["getMessage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sms-gw/v1/messages/{message_id}/dlrs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                message_id: components["parameters"]["messageId"];
            };
            cookie?: never;
        };
        get: operations["listMessageReceipts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sms-gw/v1/dashboard/instant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["dashboardInstant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sms-gw/v1/dashboard/range": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["dashboardRange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            reason: string;
            detail?: {
                [key: string]: unknown;
            };
        };
        /** Format: int64 */
        ID: number;
        /**
         * @description only sms is sent; viber is a reserved legacy channel
         * @enum {string}
         */
        Channel: "sms" | "viber";
        /** Format: date-time */
        Timestamp: string;
        Name: string;
        ListMeta: {
            total: number;
            page: number;
            page_size: number;
            sort: string;
            /** @enum {string} */
            order: "asc" | "desc";
        };
        /** @description string values keyed by the provider type's field keys; credential fields are write-only */
        ProviderConfig: {
            [key: string]: string;
        };
        Provider: {
            id: components["schemas"]["ID"];
            name: string;
            type: string;
            channel: components["schemas"]["Channel"];
            enabled: boolean;
            /** @description days messages are kept; 0 keeps them */
            retention_days: number;
            config: components["schemas"]["ProviderConfig"];
            created_at: components["schemas"]["Timestamp"];
            updated_at: components["schemas"]["Timestamp"];
        };
        ProviderCreated: components["schemas"]["Provider"] & {
            /** @description credentials the service generated (dlr_token when left blank), shown once */
            generated_secrets?: {
                [key: string]: string;
            };
        };
        ProviderPage: components["schemas"]["ListMeta"] & {
            items: components["schemas"]["Provider"][];
        };
        ProviderCreate: {
            name: components["schemas"]["Name"];
            type: string;
            channel?: components["schemas"]["Channel"];
            enabled?: boolean;
            retention_days?: number;
            config: components["schemas"]["ProviderConfig"];
        };
        /** @description absent fields keep their value; config replaces the non-credential fields */
        ProviderUpdate: {
            name?: components["schemas"]["Name"];
            type?: string;
            channel?: components["schemas"]["Channel"];
            enabled?: boolean;
            retention_days?: number;
            config?: components["schemas"]["ProviderConfig"];
        };
        ProviderField: {
            key: string;
            label: string;
            /** @enum {string} */
            type: "string" | "secret" | "url" | "int" | "select";
            required: boolean;
            default?: string;
            placeholder?: string;
            help?: string;
            options?: string[];
        };
        ProviderType: {
            type: string;
            label: string;
            description?: string;
            fields: components["schemas"]["ProviderField"][];
        };
        ProviderTypeList: {
            items: components["schemas"]["ProviderType"][];
        };
        /** @description named template fragments (Go text/template); SMS uses body */
        Fragments: {
            [key: string]: string;
        };
        Template: {
            id: components["schemas"]["ID"];
            name: string;
            channel: components["schemas"]["Channel"];
            enabled: boolean;
            fragments: components["schemas"]["Fragments"];
            /** @description properties the body refers to */
            variables: string[];
            created_at: components["schemas"]["Timestamp"];
            updated_at: components["schemas"]["Timestamp"];
        };
        TemplatePage: components["schemas"]["ListMeta"] & {
            items: components["schemas"]["Template"][];
        };
        TemplateCreate: {
            name: components["schemas"]["Name"];
            channel?: components["schemas"]["Channel"];
            enabled?: boolean;
            fragments: components["schemas"]["Fragments"];
        };
        TemplateUpdate: {
            name?: components["schemas"]["Name"];
            channel?: components["schemas"]["Channel"];
            enabled?: boolean;
            fragments?: components["schemas"]["Fragments"];
        };
        Properties: {
            [key: string]: string;
        };
        /** @enum {string} */
        Encoding: "utf-8" | "gsm-03-38";
        PreviewRequest: {
            properties?: components["schemas"]["Properties"];
            encoding?: components["schemas"]["Encoding"];
        };
        Preview: {
            /** @description rendered body; missing properties render as <no value> (as on send) */
            text: string;
            characters: number;
            /** @description SMS parts (0 for empty text, at most 10) */
            parts: number;
            /** @description character ceiling of the current part count */
            limit: number;
            encoding: components["schemas"]["Encoding"];
            variables: string[];
            /** @description variables without a property */
            missing: string[];
        };
        /**
         * @description API_ADMIN is legacy data with no public privilege
         * @enum {string}
         */
        Authority: "API_CLIENT" | "API_VIEWER" | "API_ADMIN";
        APIClient: {
            id: components["schemas"]["ID"];
            username: string;
            email: string;
            authority: components["schemas"]["Authority"];
            enabled: boolean;
            callback_url: string;
            callback_secret_set: boolean;
            last_login_at?: components["schemas"]["Timestamp"];
            last_login_ip?: string;
            created_at: components["schemas"]["Timestamp"];
            updated_at: components["schemas"]["Timestamp"];
        };
        APIClientPage: components["schemas"]["ListMeta"] & {
            items: components["schemas"]["APIClient"][];
        };
        Password: string;
        /** @description https (http only in development); public destinations only; "" clears */
        CallbackURL: string;
        /** @description write-only; "__set__" or omitted keeps, "" clears */
        CallbackSecret: string;
        APIClientCreate: {
            /** @description globally unique and immutable */
            username: string;
            password?: components["schemas"]["Password"];
            email?: string;
            /** @enum {string} */
            authority?: "API_CLIENT" | "API_VIEWER";
            enabled?: boolean;
            callback_url?: components["schemas"]["CallbackURL"];
            callback_secret?: components["schemas"]["CallbackSecret"];
        };
        APIClientCreated: {
            client: components["schemas"]["APIClient"];
            /** @description generated password (only when none was supplied), shown once */
            password?: string;
        };
        APIClientUpdate: {
            email?: string;
            /** @enum {string} */
            authority?: "API_CLIENT" | "API_VIEWER";
            enabled?: boolean;
            callback_url?: components["schemas"]["CallbackURL"];
            callback_secret?: components["schemas"]["CallbackSecret"];
        };
        PasswordReset: {
            password?: components["schemas"]["Password"];
        };
        PasswordResetResult: {
            /** @description generated password (only when none was supplied), shown once */
            password?: string;
        };
        Recipient: string;
        Block: {
            id: components["schemas"]["ID"];
            recipient: string;
            description: string;
            /** @description null blocks every provider of the tenant */
            provider_id: number | null;
            channel: components["schemas"]["Channel"];
            /** @description disabled blocks are not enforced */
            enabled: boolean;
            created_by: string;
            created_at: components["schemas"]["Timestamp"];
            updated_at: components["schemas"]["Timestamp"];
        };
        BlockPage: components["schemas"]["ListMeta"] & {
            items: components["schemas"]["Block"][];
        };
        BlockCreate: {
            recipient: components["schemas"]["Recipient"];
            description?: string;
            /** Format: int64 */
            provider_id?: number | null;
            channel?: components["schemas"]["Channel"];
            enabled?: boolean;
        };
        BlockUpdate: {
            recipient?: components["schemas"]["Recipient"];
            description?: string;
            /**
             * Format: int64
             * @description null: every provider
             */
            provider_id?: number | null;
            channel?: components["schemas"]["Channel"];
            enabled?: boolean;
        };
        Actor: {
            /** @enum {string} */
            kind: "api_client" | "platform";
            api_client_id?: number;
            api_client_username?: string;
            /** @description platform operator (manual send) */
            user_id?: string;
        };
        Message: {
            /** Format: uuid */
            id: string;
            recipient: string;
            provider_id: number;
            provider_name: string;
            template_id: number | null;
            sid: number;
            priority: number;
            text: string;
            /** @description -1 accepted by the gateway, 0 accepted by the carrier, 1 delivered, 2 failed, 16 rejected, >=1000 carrier errors, 500 carrier exchange failed */
            status_code: number;
            status_message: string;
            actor: components["schemas"]["Actor"];
            dlr_ts: number;
            remote_address?: string;
            created_at: components["schemas"]["Timestamp"];
            updated_at: components["schemas"]["Timestamp"];
        };
        MessageDetail: components["schemas"]["Message"] & {
            /** @description SMS options and properties of the send */
            data?: {
                [key: string]: unknown;
            };
            /** @description carrier exchange with credentials removed */
            evidence?: {
                request?: string;
                response?: string;
            };
        };
        MessagePage: components["schemas"]["ListMeta"] & {
            items: components["schemas"]["Message"][];
        };
        Receipt: {
            id: number;
            status: number;
            status_text: string;
            channel: string;
            sid: number;
            recipient: string;
            sender: string;
            timestamp: number;
            parts_received: number;
            remote_address?: string;
            created_at: components["schemas"]["Timestamp"];
            updated_at: components["schemas"]["Timestamp"];
        };
        ReceiptList: {
            items: components["schemas"]["Receipt"][];
            total: number;
        };
        SendRequest: {
            provider_id: components["schemas"]["ID"];
            template_id: components["schemas"]["ID"];
            /** @description MSISDN digits; the recipient policy applies */
            to: string;
            properties?: components["schemas"]["Properties"];
            sms?: {
                from?: string;
                encoding?: components["schemas"]["Encoding"];
                concatenate?: number;
            };
        };
        SendResult: {
            message: components["schemas"]["Message"];
            carrier?: {
                return_code?: number;
                return_message?: string;
            } | null;
        };
        /** @enum {string} */
        Window: "15m" | "1h" | "6h" | "24h" | "7d";
        DashboardQuery: {
            window: components["schemas"]["Window"];
            /** @description names of the predefined queries (default: all of the kind) */
            queries?: string[];
        };
        InstantSample: {
            labels: {
                [key: string]: string;
            };
            value?: number;
            has_value: boolean;
        };
        RangeSeries: {
            labels: {
                [key: string]: string;
            };
            timestamps: number[];
            values: (number | null)[];
        };
        InstantResult: {
            /** @description false: monitoring not configured or unreachable (reason) */
            available: boolean;
            /** @enum {string} */
            reason?: "not_configured" | "unreachable";
            window: components["schemas"]["Window"];
            results: {
                [key: string]: components["schemas"]["InstantSample"][];
            };
        };
        RangeResult: {
            available: boolean;
            /** @enum {string} */
            reason?: "not_configured" | "unreachable";
            window: components["schemas"]["Window"];
            start?: number;
            end?: number;
            step_seconds?: number;
            results: {
                [key: string]: components["schemas"]["RangeSeries"][];
            };
        };
    };
    responses: {
        /** @description refusal */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description deleted */
        NoContent: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
    };
    parameters: {
        page: number;
        pageSize: number;
        order: "asc" | "desc";
        /** @description case-insensitive substring search */
        q: string;
        providerId: components["schemas"]["ID"];
        templateId: components["schemas"]["ID"];
        clientId: components["schemas"]["ID"];
        blockId: components["schemas"]["ID"];
        messageId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listProviders: {
        parameters: {
            query?: {
                /** @description case-insensitive substring search */
                q?: components["parameters"]["q"];
                page?: components["parameters"]["page"];
                page_size?: components["parameters"]["pageSize"];
                sort?: "name" | "type" | "status" | "created_at" | "updated_at";
                order?: components["parameters"]["order"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description providers of the tenant, credentials redacted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderPage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createProvider: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderCreate"];
            };
        };
        responses: {
            /** @description created; config validated against the type; a blank dlr_token is generated and returned once */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderCreated"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: components["parameters"]["providerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description provider */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Provider"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: components["parameters"]["providerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["NoContent"];
            default: components["responses"]["Error"];
        };
    };
    updateProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: components["parameters"]["providerId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderUpdate"];
            };
        };
        responses: {
            /** @description updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Provider"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listProviderTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description registered provider types and their form fields */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderTypeList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listTemplates: {
        parameters: {
            query?: {
                /** @description case-insensitive substring search */
                q?: components["parameters"]["q"];
                page?: components["parameters"]["page"];
                page_size?: components["parameters"]["pageSize"];
                sort?: "name" | "status" | "created_at" | "updated_at";
                order?: components["parameters"]["order"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description templates of the tenant */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplatePage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateCreate"];
            };
        };
        responses: {
            /** @description created; an sms template needs a body fragment that parses */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Template"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: components["parameters"]["templateId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description template */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Template"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: components["parameters"]["templateId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["NoContent"];
            default: components["responses"]["Error"];
        };
    };
    updateTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: components["parameters"]["templateId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateUpdate"];
            };
        };
        responses: {
            /** @description updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Template"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    previewTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: components["parameters"]["templateId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreviewRequest"];
            };
        };
        responses: {
            /** @description rendered body, variables and part counts (same rules as send; nothing is sent) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Preview"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listAPIClients: {
        parameters: {
            query?: {
                /** @description case-insensitive substring search */
                q?: components["parameters"]["q"];
                page?: components["parameters"]["page"];
                page_size?: components["parameters"]["pageSize"];
                sort?: "username" | "authority" | "status" | "last_login_at" | "created_at";
                order?: components["parameters"]["order"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Hermes API clients of the tenant */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIClientPage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createAPIClient: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["APIClientCreate"];
            };
        };
        responses: {
            /** @description created; a generated password is returned once */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIClientCreated"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getAPIClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: components["parameters"]["clientId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API client */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIClient"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteAPIClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: components["parameters"]["clientId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["NoContent"];
            default: components["responses"]["Error"];
        };
    };
    updateAPIClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: components["parameters"]["clientId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["APIClientUpdate"];
            };
        };
        responses: {
            /** @description updated; the username cannot change */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIClient"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    resetAPIClientPassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: components["parameters"]["clientId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PasswordReset"];
            };
        };
        responses: {
            /** @description password replaced; a generated one is returned once */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasswordResetResult"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listBlocks: {
        parameters: {
            query?: {
                /** @description case-insensitive substring search */
                q?: components["parameters"]["q"];
                page?: components["parameters"]["page"];
                page_size?: components["parameters"]["pageSize"];
                sort?: "recipient" | "status" | "created_at";
                order?: components["parameters"]["order"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description recipient blocks of the tenant */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockPage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createBlock: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlockCreate"];
            };
        };
        responses: {
            /** @description created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Block"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getBlock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                block_id: components["parameters"]["blockId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description block */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Block"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteBlock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                block_id: components["parameters"]["blockId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["NoContent"];
            default: components["responses"]["Error"];
        };
    };
    updateBlock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                block_id: components["parameters"]["blockId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BlockUpdate"];
            };
        };
        responses: {
            /** @description updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Block"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listMessages: {
        parameters: {
            query?: {
                /** @description recipient prefix */
                recipient?: string;
                sid?: number;
                status?: number;
                provider_id?: components["schemas"]["ID"];
                api_client_username?: string;
                page?: components["parameters"]["page"];
                page_size?: components["parameters"]["pageSize"];
                sort?: "created_at" | "recipient" | "status";
                order?: components["parameters"]["order"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description messages of the tenant (Hermes and manual sends), newest first by default */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagePage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    sendMessage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendRequest"];
            };
        };
        responses: {
            /** @description sent through the public send pipeline; the verified operator is recorded as the actor; no client callback */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendResult"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                message_id: components["parameters"]["messageId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description message with sanitized carrier evidence */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageDetail"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listMessageReceipts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                message_id: components["parameters"]["messageId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description delivery receipts of the message, oldest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceiptList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    dashboardInstant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DashboardQuery"];
            };
        };
        responses: {
            /** @description predefined instant queries: sends_per_sec, success_rate, send_p95_seconds, dlrs_per_sec, delivery_p95_seconds, send_by_outcome, dlr_by_status, webhook_by_outcome, login_by_outcome, top_providers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstantResult"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    dashboardRange: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DashboardQuery"];
            };
        };
        responses: {
            /** @description predefined range queries over the window: send_rate_by_outcome, send_latency_p95, dlr_rate_by_status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RangeResult"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
