SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;
SET default_tablespace = '';
SET default_table_access_method = heap;
CREATE TABLE public.sms_api_client (
    id bigint NOT NULL,
    create_time timestamp with time zone,
    update_time timestamp with time zone,
    delete_time timestamp with time zone,
    username character varying NOT NULL,
    password_hash character varying NOT NULL,
    email character varying,
    authority character varying DEFAULT 'API_CLIENT'::character varying NOT NULL,
    status character varying DEFAULT 'ON'::character varying NOT NULL,
    last_login_time timestamp with time zone,
    last_login_ip character varying DEFAULT ''::character varying,
    dlr_callback_url character varying DEFAULT ''::character varying,
    dlr_callback_secret character varying DEFAULT ''::character varying
);
COMMENT ON COLUMN public.sms_api_client.id IS 'id';
COMMENT ON COLUMN public.sms_api_client.create_time IS '创建时间';
COMMENT ON COLUMN public.sms_api_client.update_time IS '更新时间';
COMMENT ON COLUMN public.sms_api_client.delete_time IS '删除时间';
COMMENT ON COLUMN public.sms_api_client.username IS 'Login name';
COMMENT ON COLUMN public.sms_api_client.password_hash IS 'bcrypt hash of the password';
COMMENT ON COLUMN public.sms_api_client.authority IS 'Role on the public API';
COMMENT ON COLUMN public.sms_api_client.status IS '''ON'' or ''OFF''';
COMMENT ON COLUMN public.sms_api_client.dlr_callback_secret IS 'HMAC-SHA256 secret signed into X-SmsGw-Signature header';
ALTER TABLE public.sms_api_client ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sms_api_client_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.sms_block (
    id bigint NOT NULL,
    create_by bigint,
    create_time timestamp with time zone,
    update_time timestamp with time zone,
    delete_time timestamp with time zone,
    recipient character varying NOT NULL,
    description character varying,
    provider_id bigint,
    block_type character varying DEFAULT 'OBJECT_TYPE_SMS'::character varying NOT NULL,
    status character varying DEFAULT 'ON'::character varying NOT NULL
);
COMMENT ON COLUMN public.sms_block.id IS 'id';
COMMENT ON COLUMN public.sms_block.create_by IS '创建者ID';
COMMENT ON COLUMN public.sms_block.create_time IS '创建时间';
COMMENT ON COLUMN public.sms_block.update_time IS '更新时间';
COMMENT ON COLUMN public.sms_block.delete_time IS '删除时间';
COMMENT ON COLUMN public.sms_block.recipient IS 'MSISDN as decimal string';
COMMENT ON COLUMN public.sms_block.description IS 'Why this entry was added';
COMMENT ON COLUMN public.sms_block.provider_id IS 'Restricts the block to one provider; 0 = global';
COMMENT ON COLUMN public.sms_block.block_type IS 'Channel scope';
COMMENT ON COLUMN public.sms_block.status IS '''ON'' enforces the block; ''OFF'' keeps the row but disables enforcement';
ALTER TABLE public.sms_block ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sms_block_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.sms_dlr (
    id bigint NOT NULL,
    create_time timestamp with time zone,
    update_time timestamp with time zone,
    delete_time timestamp with time zone,
    channel character varying NOT NULL,
    sid bigint NOT NULL,
    status_text character varying,
    message_status bigint NOT NULL,
    recipient bigint NOT NULL,
    sender character varying DEFAULT ''::character varying NOT NULL,
    "timestamp" bigint NOT NULL,
    remote_address character varying DEFAULT ''::character varying,
    parts_received bigint DEFAULT 1 NOT NULL,
    message_id character varying
);
COMMENT ON COLUMN public.sms_dlr.create_time IS '创建时间';
COMMENT ON COLUMN public.sms_dlr.update_time IS '更新时间';
COMMENT ON COLUMN public.sms_dlr.delete_time IS '删除时间';
COMMENT ON COLUMN public.sms_dlr.channel IS 'Channel name from provider, typically ''sms''';
COMMENT ON COLUMN public.sms_dlr.sid IS 'Provider session id';
COMMENT ON COLUMN public.sms_dlr.status_text IS 'Human-readable status from provider';
COMMENT ON COLUMN public.sms_dlr.message_status IS 'Provider numeric status code';
COMMENT ON COLUMN public.sms_dlr.recipient IS 'MSISDN as uint64 (kept for legacy wire shape)';
COMMENT ON COLUMN public.sms_dlr.sender IS 'Sender id';
COMMENT ON COLUMN public.sms_dlr."timestamp" IS 'Unix timestamp from provider';
COMMENT ON COLUMN public.sms_dlr.remote_address IS 'Provider IP at receive time';
COMMENT ON COLUMN public.sms_dlr.parts_received IS 'Number of carrier DLRs collapsed into this row (multipart SMS)';
COMMENT ON COLUMN public.sms_dlr.message_id IS 'FK to sms_message.id (UUID)';
ALTER TABLE public.sms_dlr ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sms_dlr_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.sms_login_log (
    id bigint NOT NULL,
    client_id bigint,
    username character varying DEFAULT ''::character varying NOT NULL,
    event_time timestamp with time zone NOT NULL,
    success boolean DEFAULT false NOT NULL,
    error_message character varying DEFAULT ''::character varying,
    login_ip character varying DEFAULT ''::character varying,
    user_agent character varying DEFAULT ''::character varying
);
COMMENT ON COLUMN public.sms_login_log.id IS 'id';
COMMENT ON COLUMN public.sms_login_log.client_id IS 'Resolved API client id; 0 when the username didn''t exist';
COMMENT ON COLUMN public.sms_login_log.username IS 'Username supplied at login (kept even on failure for forensics)';
COMMENT ON COLUMN public.sms_login_log.event_time IS 'When the attempt happened';
ALTER TABLE public.sms_login_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sms_login_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.sms_message (
    id character varying NOT NULL,
    create_by bigint,
    create_time timestamp with time zone,
    update_time timestamp with time zone,
    delete_time timestamp with time zone,
    sid bigint NOT NULL,
    recipient character varying NOT NULL,
    priority bigint DEFAULT 2 NOT NULL,
    provider_id bigint NOT NULL,
    template_id bigint DEFAULT 0 NOT NULL,
    defer character varying DEFAULT ''::character varying,
    user_name character varying,
    raw_response bytea,
    raw_request bytea,
    data jsonb,
    dlr_ts bigint DEFAULT 0,
    status_code integer DEFAULT '-1'::integer NOT NULL,
    message character varying NOT NULL,
    status_message character varying DEFAULT 'Message arrived at sms-gw'::character varying,
    remote_address character varying DEFAULT ''::character varying
);
COMMENT ON COLUMN public.sms_message.id IS 'UUID primary key';
COMMENT ON COLUMN public.sms_message.create_by IS '创建者ID';
COMMENT ON COLUMN public.sms_message.create_time IS '创建时间';
COMMENT ON COLUMN public.sms_message.update_time IS '更新时间';
COMMENT ON COLUMN public.sms_message.delete_time IS '删除时间';
COMMENT ON COLUMN public.sms_message.sid IS 'Provider session id (carrier-assigned)';
COMMENT ON COLUMN public.sms_message.recipient IS 'Destination MSISDN as a decimal string';
COMMENT ON COLUMN public.sms_message.priority IS 'Voicecom priority 1..10';
COMMENT ON COLUMN public.sms_message.provider_id IS 'FK to sms_provider.id';
COMMENT ON COLUMN public.sms_message.template_id IS 'FK to sms_template.id; 0 means no template was used';
COMMENT ON COLUMN public.sms_message.defer IS 'Reserved for v2 deferred sending';
COMMENT ON COLUMN public.sms_message.user_name IS 'Username of the API client that initiated the send';
COMMENT ON COLUMN public.sms_message.raw_response IS 'gzip-compressed HTTP response from the provider';
COMMENT ON COLUMN public.sms_message.raw_request IS 'gzip-compressed HTTP request sent to the provider';
COMMENT ON COLUMN public.sms_message.data IS 'Original request payload (Sms struct + properties)';
COMMENT ON COLUMN public.sms_message.dlr_ts IS 'Last DLR timestamp received from provider';
COMMENT ON COLUMN public.sms_message.status_code IS 'Final SMS status code; -1 = accepted, see status_codes.go';
COMMENT ON COLUMN public.sms_message.message IS 'Rendered SMS body';
COMMENT ON COLUMN public.sms_message.status_message IS 'Human-readable last status';
COMMENT ON COLUMN public.sms_message.remote_address IS 'Client IP at create time';
CREATE TABLE public.sms_provider (
    id bigint NOT NULL,
    create_time timestamp with time zone,
    update_time timestamp with time zone,
    delete_time timestamp with time zone,
    name character varying NOT NULL,
    type character varying NOT NULL,
    object_type character varying DEFAULT 'OBJECT_TYPE_SMS'::character varying NOT NULL,
    config jsonb,
    status character varying DEFAULT 'ON'::character varying NOT NULL,
    retention_days bigint DEFAULT 0 NOT NULL
);
COMMENT ON COLUMN public.sms_provider.id IS 'id';
COMMENT ON COLUMN public.sms_provider.create_time IS '创建时间';
COMMENT ON COLUMN public.sms_provider.update_time IS '更新时间';
COMMENT ON COLUMN public.sms_provider.delete_time IS '删除时间';
COMMENT ON COLUMN public.sms_provider.name IS 'Display name';
COMMENT ON COLUMN public.sms_provider.type IS 'Implementation key (e.g. ''voicecom'')';
COMMENT ON COLUMN public.sms_provider.object_type IS 'Channel kind';
COMMENT ON COLUMN public.sms_provider.config IS 'Provider-specific configuration map';
COMMENT ON COLUMN public.sms_provider.status IS '''ON'' or ''OFF'' — OFF rejects Send';
COMMENT ON COLUMN public.sms_provider.retention_days IS 'Days to keep messages created via this provider; 0 = never delete';
ALTER TABLE public.sms_provider ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sms_provider_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.sms_template (
    id bigint NOT NULL,
    create_time timestamp with time zone,
    update_time timestamp with time zone,
    delete_time timestamp with time zone,
    name character varying NOT NULL,
    object_type character varying DEFAULT 'OBJECT_TYPE_SMS'::character varying NOT NULL,
    templates jsonb,
    status character varying DEFAULT 'ON'::character varying NOT NULL
);
COMMENT ON COLUMN public.sms_template.id IS 'id';
COMMENT ON COLUMN public.sms_template.create_time IS '创建时间';
COMMENT ON COLUMN public.sms_template.update_time IS '更新时间';
COMMENT ON COLUMN public.sms_template.delete_time IS '删除时间';
COMMENT ON COLUMN public.sms_template.name IS 'Display name';
COMMENT ON COLUMN public.sms_template.templates IS 'Map of named template fragments. SMS uses ''body''.';
ALTER TABLE public.sms_template ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sms_template_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY public.sms_api_client
    ADD CONSTRAINT sms_api_client_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.sms_block
    ADD CONSTRAINT sms_block_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.sms_dlr
    ADD CONSTRAINT sms_dlr_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.sms_login_log
    ADD CONSTRAINT sms_login_log_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.sms_message
    ADD CONSTRAINT sms_message_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.sms_provider
    ADD CONSTRAINT sms_provider_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.sms_template
    ADD CONSTRAINT sms_template_pkey PRIMARY KEY (id);
CREATE INDEX apiclient_status ON public.sms_api_client USING btree (status);
CREATE UNIQUE INDEX apiclient_username ON public.sms_api_client USING btree (username);
CREATE INDEX block_provider_id_recipient ON public.sms_block USING btree (provider_id, recipient);
CREATE INDEX block_recipient ON public.sms_block USING btree (recipient);
CREATE INDEX dlr_message_id_create_time ON public.sms_dlr USING btree (message_id, create_time);
CREATE UNIQUE INDEX dlr_message_id_message_status ON public.sms_dlr USING btree (message_id, message_status);
CREATE INDEX loginlog_client_id_event_time ON public.sms_login_log USING btree (client_id, event_time);
CREATE INDEX loginlog_event_time ON public.sms_login_log USING btree (event_time);
CREATE INDEX loginlog_username_event_time ON public.sms_login_log USING btree (username, event_time);
CREATE INDEX provider_status ON public.sms_provider USING btree (status);
CREATE INDEX provider_type ON public.sms_provider USING btree (type);
CREATE UNIQUE INDEX sms_api_client_username_key ON public.sms_api_client USING btree (username);
CREATE UNIQUE INDEX sms_provider_name_key ON public.sms_provider USING btree (name);
CREATE UNIQUE INDEX sms_template_name_key ON public.sms_template USING btree (name);
CREATE INDEX smsmessage_create_by ON public.sms_message USING btree (create_by);
CREATE INDEX smsmessage_provider_id_recipient_create_time ON public.sms_message USING btree (provider_id, recipient, create_time);
CREATE INDEX smsmessage_status_code ON public.sms_message USING btree (status_code);
ALTER TABLE ONLY public.sms_dlr
    ADD CONSTRAINT sms_dlr_sms_message_dlrs FOREIGN KEY (message_id) REFERENCES public.sms_message(id) ON DELETE SET NULL;
