-- +goose Up
-- Tenant-scoped SMS gateway schema. Table names and numeric/UUID ids follow
-- the legacy sms_* tables so imported ids, sequences and public wire values
-- stay stable. Every row carries its tenant; references are composite
-- (tenant_id, id) foreign keys, so a reference can never cross tenants.

-- +goose StatementBegin
CREATE FUNCTION app_tenant_matches(tid uuid) RETURNS boolean
LANGUAGE sql STABLE AS $$
  SELECT tid::text = current_setting('app.tenant_id', true)
      OR current_setting('app.system', true) = 'on'
$$;
-- +goose StatementEnd

CREATE TABLE sms_api_client (
  id                         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id BETWEEN 1 AND 4294967295),
  tenant_id                  uuid NOT NULL,
  username                   text NOT NULL CHECK (username ~ '^[A-Za-z0-9_]{4,50}$'),
  password_hash              text NOT NULL CHECK (length(password_hash) BETWEEN 1 AND 128),
  email                      text NOT NULL DEFAULT '' CHECK (length(email) <= 255),
  authority                  text NOT NULL DEFAULT 'API_CLIENT' CHECK (authority IN ('API_CLIENT', 'API_VIEWER', 'API_ADMIN')),
  status                     text NOT NULL DEFAULT 'ON' CHECK (status IN ('ON', 'OFF')),
  last_login_time            timestamptz,
  last_login_ip              text NOT NULL DEFAULT '' CHECK (length(last_login_ip) <= 64),
  dlr_callback_url           text NOT NULL DEFAULT '' CHECK (length(dlr_callback_url) <= 2048),
  dlr_callback_secret_sealed bytea,
  create_time                timestamptz NOT NULL DEFAULT now(),
  update_time                timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, id)
);
-- Hermes login carries no tenant: usernames stay globally unique.
CREATE UNIQUE INDEX sms_api_client_username ON sms_api_client (username);

CREATE TABLE sms_provider (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id BETWEEN 1 AND 4294967295),
  tenant_id      uuid NOT NULL,
  name           text NOT NULL CHECK (length(name) BETWEEN 1 AND 128),
  type           text NOT NULL CHECK (length(type) BETWEEN 1 AND 32),
  object_type    text NOT NULL DEFAULT 'OBJECT_TYPE_SMS' CHECK (object_type IN ('OBJECT_TYPE_SMS', 'OBJECT_TYPE_VIBER')),
  config_sealed  bytea NOT NULL,
  config_public  jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(config_public) = 'object'),
  status         text NOT NULL DEFAULT 'ON' CHECK (status IN ('ON', 'OFF')),
  retention_days integer NOT NULL DEFAULT 0 CHECK (retention_days >= 0),
  create_time    timestamptz NOT NULL DEFAULT now(),
  update_time    timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, id),
  UNIQUE (tenant_id, name)
);

CREATE TABLE sms_template (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id BETWEEN 1 AND 4294967295),
  tenant_id   uuid NOT NULL,
  name        text NOT NULL CHECK (length(name) BETWEEN 1 AND 128),
  object_type text NOT NULL DEFAULT 'OBJECT_TYPE_SMS' CHECK (object_type IN ('OBJECT_TYPE_SMS', 'OBJECT_TYPE_VIBER')),
  templates   jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(templates) = 'object'),
  status      text NOT NULL DEFAULT 'ON' CHECK (status IN ('ON', 'OFF')),
  create_time timestamptz NOT NULL DEFAULT now(),
  update_time timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, id),
  UNIQUE (tenant_id, name)
);

-- provider_id NULL is the legacy 0: every provider of the tenant.
CREATE TABLE sms_block (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id BETWEEN 1 AND 4294967295),
  tenant_id   uuid NOT NULL,
  recipient   text NOT NULL CHECK (length(recipient) BETWEEN 1 AND 64),
  description text NOT NULL DEFAULT '' CHECK (length(description) <= 255),
  provider_id bigint,
  block_type  text NOT NULL DEFAULT 'OBJECT_TYPE_SMS' CHECK (block_type IN ('OBJECT_TYPE_SMS', 'OBJECT_TYPE_VIBER')),
  status      text NOT NULL DEFAULT 'ON' CHECK (status IN ('ON', 'OFF')),
  created_by  text NOT NULL DEFAULT '' CHECK (length(created_by) <= 128),
  create_time timestamptz NOT NULL DEFAULT now(),
  update_time timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, id),
  FOREIGN KEY (tenant_id, provider_id) REFERENCES sms_provider (tenant_id, id) ON DELETE RESTRICT
);
CREATE INDEX sms_block_lookup ON sms_block (tenant_id, recipient) WHERE status = 'ON';

-- One gateway record per accepted send. The actor is either a Hermes API
-- client (legacy numeric owner) or a verified platform operator, never both.
CREATE TABLE sms_message (
  id             uuid PRIMARY KEY,
  tenant_id      uuid NOT NULL,
  actor_kind     text NOT NULL CHECK (actor_kind IN ('api_client', 'platform')),
  api_client_id  bigint,
  platform_actor text,
  sid            bigint NOT NULL DEFAULT 0 CHECK (sid BETWEEN 0 AND 4294967295),
  recipient      text NOT NULL CHECK (recipient ~ '^[0-9]{1,20}$'),
  priority       integer NOT NULL DEFAULT 2 CHECK (priority >= 0),
  provider_id    bigint NOT NULL,
  template_id    bigint,
  defer          text NOT NULL DEFAULT '' CHECK (length(defer) <= 64),
  user_name      text NOT NULL DEFAULT '' CHECK (length(user_name) <= 128),
  raw_request    bytea,
  raw_response   bytea,
  data           jsonb,
  dlr_ts         bigint NOT NULL DEFAULT 0,
  status_code    integer NOT NULL DEFAULT -1,
  message        text NOT NULL,
  status_message text NOT NULL DEFAULT 'sms_gw_accepted',
  remote_address text NOT NULL DEFAULT '' CHECK (length(remote_address) <= 64),
  create_time    timestamptz NOT NULL DEFAULT now(),
  update_time    timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, id),
  CHECK ((actor_kind = 'api_client' AND api_client_id IS NOT NULL AND platform_actor IS NULL)
      OR (actor_kind = 'platform' AND api_client_id IS NULL AND length(platform_actor) BETWEEN 1 AND 128)),
  FOREIGN KEY (tenant_id, provider_id) REFERENCES sms_provider (tenant_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (tenant_id, template_id) REFERENCES sms_template (tenant_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (tenant_id, api_client_id) REFERENCES sms_api_client (tenant_id, id) ON DELETE RESTRICT
);
CREATE INDEX sms_message_tenant_time ON sms_message (tenant_id, create_time DESC, id DESC);
CREATE INDEX sms_message_client_time ON sms_message (tenant_id, api_client_id, create_time DESC, id DESC) WHERE api_client_id IS NOT NULL;
CREATE INDEX sms_message_provider_time ON sms_message (tenant_id, provider_id, create_time);
CREATE INDEX sms_message_recipient ON sms_message (tenant_id, recipient text_pattern_ops);

-- Receipts aggregate per (message, status); duplicates increment parts_received.
-- Retention deletes a message and its receipts in one statement (cascade).
CREATE TABLE sms_dlr (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id      uuid NOT NULL,
  message_id     uuid NOT NULL,
  channel        text NOT NULL DEFAULT '' CHECK (length(channel) <= 32),
  sid            bigint NOT NULL DEFAULT 0,
  status_text    text NOT NULL DEFAULT '' CHECK (length(status_text) <= 128),
  message_status bigint NOT NULL CHECK (message_status BETWEEN 0 AND 4294967295),
  recipient      bigint NOT NULL DEFAULT 0 CHECK (recipient >= 0),
  sender         text NOT NULL DEFAULT '' CHECK (length(sender) <= 64),
  "timestamp"    bigint NOT NULL DEFAULT 0,
  remote_address text NOT NULL DEFAULT '' CHECK (length(remote_address) <= 64),
  parts_received integer NOT NULL DEFAULT 1 CHECK (parts_received >= 1),
  create_time    timestamptz NOT NULL DEFAULT now(),
  update_time    timestamptz NOT NULL DEFAULT now(),
  UNIQUE (message_id, message_status),
  FOREIGN KEY (tenant_id, message_id) REFERENCES sms_message (tenant_id, id) ON DELETE CASCADE
);
CREATE INDEX sms_dlr_message ON sms_dlr (tenant_id, message_id, create_time, id);

-- An unknown username resolves no tenant: such failures keep tenant_id NULL.
CREATE TABLE sms_login_log (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id     uuid,
  client_id     bigint,
  username      text NOT NULL DEFAULT '' CHECK (length(username) <= 64),
  event_time    timestamptz NOT NULL DEFAULT now(),
  success       boolean NOT NULL DEFAULT false,
  error_message text NOT NULL DEFAULT '' CHECK (length(error_message) <= 255),
  login_ip      text NOT NULL DEFAULT '' CHECK (length(login_ip) <= 64),
  user_agent    text NOT NULL DEFAULT '' CHECK (length(user_agent) <= 512),
  CHECK ((tenant_id IS NULL) = (client_id IS NULL)),
  FOREIGN KEY (tenant_id, client_id) REFERENCES sms_api_client (tenant_id, id) ON DELETE SET NULL
);
CREATE INDEX sms_login_log_tenant_time ON sms_login_log (tenant_id, event_time DESC);
CREATE INDEX sms_login_log_time ON sms_login_log (event_time);

-- Append-only audit trail with a closed vocabulary (enforced by the writer);
-- never bodies, tokens or secrets.
CREATE TABLE sms_audit (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id   uuid NOT NULL,
  actor_kind  text NOT NULL CHECK (actor_kind IN ('operator', 'api_client', 'service', 'system')),
  actor_id    text NOT NULL DEFAULT '' CHECK (length(actor_id) <= 128),
  action      text NOT NULL CHECK (action ~ '^[a-z][a-z_]*\.[a-z][a-z_]*$'),
  target_type text NOT NULL DEFAULT '' CHECK (length(target_type) <= 32),
  target_id   text NOT NULL DEFAULT '' CHECK (length(target_id) <= 128),
  outcome     text NOT NULL CHECK (outcome IN ('success', 'denied', 'failure')),
  request_id  text NOT NULL DEFAULT '' CHECK (length(request_id) <= 128),
  event_time  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX sms_audit_tenant_time ON sms_audit (tenant_id, event_time DESC);
-- +goose StatementBegin
CREATE FUNCTION sms_audit_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'sms_audit is append-only';
END $$;
-- +goose StatementEnd
CREATE TRIGGER sms_audit_append_only BEFORE UPDATE OR DELETE ON sms_audit FOR EACH ROW EXECUTE FUNCTION sms_audit_append_only();

-- Hermes logout: the token id (jti) is kept until the token would expire;
-- the bearer token itself is never stored.
CREATE TABLE sms_token_revocation (
  jti        text PRIMARY KEY CHECK (jti ~ '^[0-9a-f]{16,64}$'),
  tenant_id  uuid NOT NULL,
  client_id  bigint NOT NULL,
  expires_at timestamptz NOT NULL,
  revoked_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (tenant_id, client_id) REFERENCES sms_api_client (tenant_id, id) ON DELETE CASCADE
);
CREATE INDEX sms_token_revocation_expiry ON sms_token_revocation (expires_at);

CREATE TABLE sms_import_run (
  id                 uuid PRIMARY KEY,
  tenant_id          uuid NOT NULL,
  source_fingerprint text NOT NULL CHECK (source_fingerprint ~ '^[0-9a-f]{64}$'),
  mode               text NOT NULL CHECK (mode IN ('dry_run', 'apply')),
  status             text NOT NULL DEFAULT 'running' CHECK (status IN ('running', 'succeeded', 'failed')),
  checkpoint         jsonb NOT NULL DEFAULT '{}'::jsonb,
  counts             jsonb NOT NULL DEFAULT '{}'::jsonb,
  report             jsonb NOT NULL DEFAULT '{}'::jsonb,
  started_at         timestamptz NOT NULL DEFAULT now(),
  finished_at        timestamptz
);
CREATE UNIQUE INDEX sms_import_run_applied ON sms_import_run (tenant_id, source_fingerprint) WHERE mode = 'apply' AND status = 'succeeded';

-- Row-level security backs the explicit tenant predicates: the application
-- role (no BYPASSRLS) sets app.tenant_id per transaction; cross-tenant work
-- (Hermes login, receipt tenant resolution, retention) runs with app.system.
-- +goose StatementBegin
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['sms_api_client','sms_provider','sms_template','sms_block','sms_message','sms_dlr','sms_login_log','sms_audit','sms_token_revocation','sms_import_run']
  LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format('CREATE POLICY tenant_isolation ON %I USING (app_tenant_matches(tenant_id)) WITH CHECK (app_tenant_matches(tenant_id))', t);
  END LOOP;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'smsgw_app') THEN
    GRANT USAGE ON SCHEMA public TO smsgw_app;
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO smsgw_app;
    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO smsgw_app;
    REVOKE UPDATE, DELETE ON sms_audit FROM smsgw_app;
  END IF;
END $$;
-- +goose StatementEnd

-- +goose Down
DROP TABLE IF EXISTS sms_import_run, sms_token_revocation, sms_audit, sms_login_log, sms_dlr, sms_message, sms_block, sms_template, sms_provider, sms_api_client;
DROP FUNCTION IF EXISTS sms_audit_append_only();
DROP FUNCTION IF EXISTS app_tenant_matches(uuid);
