#!/bin/sh
# First start of the bundle's database: the application role (no
# BYPASSRLS: row-level security backs every tenant predicate). Its password
# is generated by the gateway (hex, so it needs no quoting).
set -eu
psql -v ON_ERROR_STOP=1 --username postgres --dbname sms_gw <<SQL
CREATE ROLE smsgw_app LOGIN PASSWORD '${SMSGW_APP_PASSWORD}' NOBYPASSRLS;
GRANT CONNECT ON DATABASE sms_gw TO smsgw_app;
SQL
