import { SET_MARKER, type ProviderField } from '@/api/types'

// Provider configuration forms are built from the type's field list
// (GET /provider-types). Credentials ("secret" fields) are write-only: a
// stored one reads as SET_MARKER and is sent back as is to keep it, "" clears
// it. Non-credential values are sent back exactly as shown (a callback URL may
// embed the marker in place of the receipt token, which keeps the stored one).

/** Initial values: the stored configuration, or each field's default for a new provider. */
export function initialConfig(fields: ProviderField[], stored?: Record<string, string>): Record<string, string> {
  const out: Record<string, string> = {}
  for (const f of fields) out[f.key] = stored ? (stored[f.key] ?? '') : (f.default ?? '')
  return out
}

/** Client-side checks; the server validates again against the type. */
export function validateConfig(fields: ProviderField[], values: Record<string, string>): Record<string, string> {
  const errors: Record<string, string> = {}
  for (const f of fields) {
    const v = (values[f.key] ?? '').trim()
    if (!v) {
      if (f.required) errors[f.key] = 'Required'
      continue
    }
    if (f.type === 'int' && !/^-?\d+$/.test(v)) errors[f.key] = 'Enter a whole number'
    else if (f.type === 'url' && !v.includes(SET_MARKER) && !/^https?:\/\/[^\s]+$/i.test(v)) errors[f.key] = 'Enter an http(s) URL'
    else if (f.type === 'select' && f.options?.length && !f.options.includes(v)) errors[f.key] = 'Choose one of the options'
  }
  return errors
}

/**
 * The config to send. Blank non-credential fields are left out (absent means
 * unset). On create blank credentials are left out too (a blank dlr_token is
 * generated by the server); on update every credential is sent so the marker
 * keeps it and "" clears it.
 */
export function buildConfig(fields: ProviderField[], values: Record<string, string>, creating: boolean): Record<string, string> {
  const out: Record<string, string> = {}
  for (const f of fields) {
    const v = (values[f.key] ?? '').trim()
    if (f.type === 'secret') {
      if (v || !creating) out[f.key] = v
    } else if (v) out[f.key] = v
  }
  return out
}
